server:
  port: 8081
  context-path: /

spring:
  profiles:
    active: mysql
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/basicSetting?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: user
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1 from dual
    validation-query-timeout: 10000
    time-between-eviction-runs-millis: 60000
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  type-aliases-package: kr.pe.tree.module
  config-location: classpath:mybatis/config/Mybatis_Config.xml
  



